package com.fit3077.a2;

public enum ProgressionUIState
{
    LOGIN,
    MAINMENU,
    COVIDBOOKING,
    VIEWBOOKING,
    SEARCHING,
    QUESTIONARE,
    ONSITETESTING,
    PINCODEGENERATION,
    QRURLGENERATION,
    QRCODESCANNING,
    HOMETESTING,
    MODIFYBOOKINGPROMPT,
    MODIFYBOOKINGONSITE,
    MODIFYBOOKINGPHONECALL,
    MODIFYBOOKINGADJUSTMENT,
    ADMINBOOKINGEDITING,
    BOOKINGHISTORY,
    SEARCHBOOKINGS

}
